common/models/Course.php
<?php

namespace common\models;

use Yii;
use omgdef\multilingual\MultilingualQuery;
use common\components\ImageBehavior;
use common\components\CMultilingualBehavior;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\helpers\VarDumper;

/**
 * This is the model class for table "course".
 *
 * @property integer $id
 * @property integer $owner_id
 * @property integer $price
 * @property string $image
 * @property string $start_date
 * @property string $end_date
 * @property integer $status
 *
 * @property Chef $owner
 * @property CourseLang[] $courseLangs
 */
class Course extends \yii\db\ActiveRecord
{
//    public
//        $width = 115,
//        $height = 115;
    public
        $img_size = [
            'min' => [
                'width' => 200,
                'height' => 150
            ],
            'full' => [
                'width' => 800,
                'height' => 600
            ]
    ];
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'course';
    }

    public function behaviors()
    {
        return [
            ImageBehavior::className(),
            'ml' => [
                'class' => CMultilingualBehavior::className(),
                'languages' => Lang::getMap(),
                'languageField' => 'language',
                'langClassName' => CourseLang::className(),
                'langForeignKey' => 'owner_id',
                'tableName' => 'chef_lang',
                'attributes' => [
                    'local_status',
                    'name',
                    'content',
                    'meta_title',
                    'meta_keywords',
                    'meta_description',
                ]
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [
                'image',
                'required',
                'when' => function($model){return $model->isNewRecord; },
                'whenClient' => '
                    function(){
                        return document.
                            getElementsByClassName("file-input")[0]
                            .classList
                            .contains("file-input-new");
                    }'
            ],
            [['owner_id', 'status'], 'required'],
            [['owner_id', 'price', 'status', 'local_status'], 'integer'],
            [['start_date', 'end_date'], 'safe'],
            [['image'], 'file', 'extensions'=>'jpg, gif, png, jpeg', 'maxSize' => 1024 * 1024],
            [['owner_id'], 'exist', 'skipOnError' => true, 'targetClass' => Chef::className(), 'targetAttribute' => ['owner_id' => 'id']],
            [['meta_title', 'meta_keywords', 'meta_description'], 'string', 'max' => 255],
            [['name', 'url'], 'string', 'max' => 64],
            [['content'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'owner_id' => Yii::t('app', 'Owner ID'),
            'price' => Yii::t('app', 'Price'),
            'image' => Yii::t('app', 'Image'),
            'start_date' => Yii::t('app', 'Start Date'),
            'end_date' => Yii::t('app', 'End Date'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOwner()
    {
        return $this->hasOne(Chef::className(), ['id' => 'owner_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCourseLangs()
    {
        return $this->hasMany(CourseLang::className(), ['owner_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return CourseQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new MultilingualQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        $this->price = (int) $this->price;
        return true;
    }

    public function getOnlineByCondition($attr, $value)
    {
        $custom_params[$attr] = $value;
        $default_params = ['status' => true];

        $params = $this->hasAttribute($attr)
            ? array_merge($default_params, $custom_params)
            : $default_params;

//        VarDumper::dump($this
//            ->find()
//            ->joinWith('translation')
//            ->where([
//                '<',
//                'start_date',
//                new Expression('NOW()')
//            ])
//            ->andWhere(['local_status' => true])
//            ->andFilterWhere($params)
//            ->orderBy(['start_date' => SORT_DESC]),10,1);die;

        return new ActiveDataProvider([
            'query' => $this
                ->find()
                ->joinWith('translation')
                ->where([
                    '<',
                    'start_date',
                    new Expression('NOW()')
                ])
                ->andWhere(['local_status' => true])
                ->andFilterWhere($params)
                ->orderBy(['start_date' => SORT_DESC]),
//              ->andWhere(['hasVideo'])  TODO append to course model some video field
            'pagination' => [
                'pageSize' => false
            ]
        ]);
    }

    public function get_IsLiked()
    {
        return Favorite::findOne([
            'owner_id'  => Yii::$app->user->identity,
            'course_id' => $this->id
        ]);
    }

    public function getFavoriteItem()
    {
        return $this->_isLiked;
    }

//    public function preparePath($extension)
//    {
//        return Yii::$app->params['uploadPathCourse'] . Yii::$app->getSecurity()->generateRandomString(6) . '.' .$extension;
//    }
}

common/controllers/CourseController.php
<?php

namespace common\controllers;

use Yii;
use common\models\Course;
use common\models\CourseSearch;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CourseController implements the CRUD actions for Course model.
 */
class CourseController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Course models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CourseSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Course model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Course model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Course();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Course model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = Course::find()->where(['id' => $id])->multilingual()->one();

//        if(Yii::$app->request->post()) {VarDumper::dump(Yii::$app->request->post(),10,1);die;}

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Course model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Course model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Course the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Course::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/CourseController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Course;
use common\models\CourseSearch;
use yii\data\ActiveDataProvider;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use common\components\CUrl;
use common\models\User;

/**
 * CourseController implements the CRUD actions for Course model.
 */
class CourseController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete'    => ['POST'],
                    'subscribe' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Course models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CourseSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Course model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($url)
    {
        $this->layout = 'main';

        $model = Course::find()->where(['url' => $url])->one();

        if(Yii::$app->request->post('Course'))
        {
            if (Yii::$app->user->isGuest) {
                Url::remember('', 'login_before');
                return $this->redirect(CUrl::to(['user/login']));
            }

            // favorite item removed in beforeSave event in Cart model
            Yii::$app
                ->user
                ->identity
                ->link('courses', $model);

            return $this->redirect(CUrl::to(['cart/index']));
        }

        Url::remember();

        return $this->render('view', [
            'model' => $model,
            'owner' => $model->owner
        ]);
    }

    // future courses
    public function actionBroadcast()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Course::find()->where([
                '>',
                'start_date',
                new Expression('NOW()')
            ])
        ]);

        return $this->render('broadcast',[
            'dataProvider' => $dataProvider
        ]);
    }

    // show alredy started && active && contain video order by start_date desc
    public function actionOnline($attr = null, $value = null)
    {
        $model = new Course();
        $dataProvider = $model->getOnlineByCondition($attr, $value);

        return $this->render('searchList',[
            'dataProvider' => $dataProvider,
            'list' => ArrayHelper::getColumn($model->find()->joinWith('translation')->all(), 'name')
        ]);
    }

//    public function actionGetList()
//    {
//        Yii::$app->response->format = Response::FORMAT_JSON;
//        return ArrayHelper::getColumn(Course::find()->joinWith('translation')->all(), 'name');
//    }

    public function actionSearch()
    {
        $query_str = Yii::$app->request->get('query');

        $dataProvider = new ActiveDataProvider([
            'query' => Course::find()->joinWith('translation')->where(['like', 'name', $query_str])
        ]);

        Yii::$app->response->format = Response::FORMAT_JSON;

        return $this->render('filteredList',[
            'dataProvider' => $dataProvider,
            'list' => ArrayHelper::getColumn(Course::find()->joinWith('translation')->all(), 'name')
        ]);
    }

    public function actionFavorite($id)
    {
        // ...и то, чего не может быть, чаще другого случается...
        if(Yii::$app->user->isGuest)
            return $this->redirect(Url::previous());

        // cart item is removed in beforeSave event in Favorite model

        Yii::$app
            ->user
            ->identity
            ->link('favoriteCourses', Course::findOne($id));

        return $this->redirect(Url::previous());
    }

    public function actionSubscribe()
    {
        $user = new User();
        $post = Yii::$app->request->post();

        if($user->findByUseremail($post['email']))
        {
            Yii::$app->session->setFlash(
                'error',
                'User with email'. $post['email'] .' alredy registered. Тимур, треба давати можливість підписки зареєстрованим?'
            );

            return $this->redirect(['site/index']);
        }
    }

    /**
     * Finds the Course model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Course the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($params)
    {
        if (($model = Course::find()->joinWith('translation')->where($params)->one()) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/course/broadcast.php
<?
use yii\widgets\ListView;

$this->title = 'Будущие Мастер-Классы';
$this->params['breadcrumbs'][] = 'Ближайшие Мастер-Классы';
?>
<div class="col-md-9">
    <?= $this->render('broadcastDesc') ?>
    <?=
    ListView::widget([
        'dataProvider' => $dataProvider,
        'layout' => '{items}',
        'options' => [
            'tag' => null
        ],
        'itemOptions' => [
            'tag' => 'div',
            'class' => 'col-md-6 col-sm-6 col-xs-12 sCol'
        ],
        'itemView' => 'listItem',
        'emptyTextOptions' => ['tag' => 'h3'],
        'emptyText' => 'На ближайшее время мероприятий не запланировано.'
    ])
    ?>
</div>
<div class="col-md-3 hidden-xs hidden-sm">
    <div>
        <?= $this->render('/course/subscribeForm') ?>
    </div>
    <div class="btnSocial">
        <?= $this->render('/site/socialButtons', ['class' => 'col-sm-6 text-center social-follow-ico']) ?>
    </div>
</div>

frontend/views/course/cartItem.php
<?
use common\components\CUrl;
use yii\helpers\Html;
?>
<div class="cart_items">
    <div class="col-xs-3">
        <div class="cart_img text-center">
            <img src="<?= $model->image ?>">
        </div>
    </div>
    <div class="col-xs-6">
        <a href='<?= CUrl::to(['cart/delete', 'id' => $model->id ]) ?>' class="course_del">Удалить</a>
        <a href='<?= CUrl::to(['course/favorite', 'id' => $model->id ]) ?>' class='course_favorite'>Добавить в избранное</a>
        <a href='<?= CUrl::to(['course/view', 'url' => $model->url ]) ?>' class="course_title"><?= $model->name ?></a>
        <span class="course_lable">Шеф: </span>
        <a class="course_chif" href='<?= CUrl::to(['chef/view', 'url' => $model->owner->url]) ?>'><?= $model->owner->name ?></a>
        <br>
        <?= $model->start_date ?>
    </div>
    <div class="col-xs-3">
        <span class="course_price"><?= Yii::$app->formatter->asDecimal($model->price - $model->price * $discount / 100) ?> €</span>
        <?
        if($discount)
        {
            echo Html::tag('span', Yii::t('app', 'saving'), ['class' => 'course_economy']);
            echo Html::tag('span', Yii::$app->formatter->asDecimal($model->price * $discount / 100).' €', ['class' => 'course_economy_summ']);
        }
        ?>
    </div>
</div>
<br>

frontend/views/course/favoriteItem.php
<?
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use common\components\CUrl;
?>
<div class="col-xs-3">
    <div class="cart_img text-center">
        <img src="<?= $model->image ?>">
    </div>
</div>
<div class="col-xs-7">
    <a href='<?= CUrl::to(['favorite/delete', 'id' => $model->id]) ?>' class="course_del">Удалить</a>
    <? $form = ActiveForm::begin(['action' => CUrl::to(['course/view', 'url' => $model->url])]); ?>
        <?= Html::submitButton('Добавить в корзину', [
                'class' => 'course_favorite',
                'name'  => 'Course',
                'value' => $model->price
        ]) ?>
    <? ActiveForm::end(); ?>
    <a href='<?= CUrl::to(['course/view', 'url' => $model->url]) ?>' class="course_title">
        <?= $model->name ?>
    </a>
    <span class="course_lable">Шеф: </span>
    <a class="course_chif" href='<?= CUrl::to(['chef/view', 'url' => $model->owner->url]) ?>'>
        <?= $model->owner->name ?>
    </a><br>
    <?= $model->start_date ?>
</div>
<div class="col-xs-2">
    <span class="course_price"><?= $model->price ?> €</span>
</div>

frontend/views/course/homeSubMainItem.php
<?
use common\components\CUrl;
?>
<div class='sBlock sub-main-item' style='background-image:url(<?= $model->image ?>);'>
    <div class='sLabel'>
        <span id='courseOlinePrice'><?= $model->price ?></span>€
    </div>
    <div class='sCover'>
        <a href='<?= CUrl::to(['course/view', 'url' => $model->url]) ?>'>
            <?= $model->name ?>
        </a>
        <div class='sChief hidden-xs'>
            <a href='<?= CUrl::to(['chef/view', 'url' => $model->owner->url]) ?>'>
                <img class='chiefPhotoSm' src='<?= $model->owner->getImage() ?>'>
            </a>
        </div>
        <div class='sCoverLabel'>
            <?= Yii::$app->formatter->asDatetime($model->end_date, "php:d.m.Y") ?>
        </div>
<!--        <div class='sCoverLabel2'>-->
<!--            Осталось: 33 мест-->
<!--        </div>-->
        <div class='sCoverLine'>
            <div class='text-right col-xs-8 pull-right padding-right20'>
                <span class='glyphicon glyphicon-comment'></span> 0 &nbsp;&nbsp;
                <span class='glyphicon glyphicon-eye-open'></span> 10262
            </div>
        </div>
    </div>

</div>

frontend/views/course/view.php
<?
use common\components\CUrl;
?>

<?
$this->title = $model->meta_title;
?>

<div style="background:url(<?= $owner->image ?>);min-height:500px;background-size:cover;background-position: 50% 60%;background-repeat:no-repeat;">
    <div class="lBlockOver">
        <div class="container">
            <div class="col-md-8 form-about">
                <a href='<?= CUrl::to(['chef/view', 'url' => $owner->url]) ?>' style="color:#fff;display:inline;">
                    <img class="chiefPhoto" src="<?= $owner->getImage() ?>" style="display:inline;">
                    <h2 style="display:inline;margin-left:20px;">
                        <?= $owner->name ?>
                    </h2>
                </a>
                <div class="favorite-add-heart">
                    <?= $model->_isLiked
                        ? "<a class='checked'> ".Yii::t('app', 'added_to_favorites')."</a>"
                        : "<a href='".CUrl::to(['course/favorite', 'id' => $model->id])."'><img src='/image/heart.png'> ".Yii::t('app', 'add_to_favorites')."</a>"
                    ?>
                </div>
                <h2 style="color:#fff;"><?= $model->name ?></h2>
                <div class="lTerm lTerm-buy lead col-xs-12 col-sm-7">

                    <p>
                        <span style="font-size: large;">
                            <?= Yii::t('app', 'duration') ?>: <br><br>1 день -<strong>8 ч 17 м</strong>
                        </span>
                    </p>
                    <p>
                        <span style="font-size: large;">2 день -<strong>7 ч 34 м</strong></span>
                    </p>
                    <p>
                        <span style="font-size: large;"><strong></strong>3 день -<strong>8 ч 45 м</strong></span>
                    </p>
                    <p>
                        <span style="font-size: large;">
                            <?= Yii::t('app', 'cost') ?>: <?= $model->price ?> EUR
                        </span>
                    </p>
                </div>
                <div id="maxShare">
                    <div id="facebook" data-url="http://kicapastry.com/course/Mark_de_Passorio/" data-text="Красный тунец от Шефа Марка Де Пассорио" data-title="Share" class="sharrre"><div class="box"><a class="count" href="#">0</a><a class="share" href="#">Share</a></div></div>

                    <div id="comment" class="sharrre">
                        <div class="box"><a class="count" name="comment_count" href="#comments">48</a><a class="share" href="#comments">COMMENT</a></div>
                    </div>

                    <div id="views" class="sharrre">
                        <div class="box"><a class="count" href="#">2835</a><a class="share" href="#">views</a></div>
                    </div>

                    <div id="shares" class="sharrre">
                        <div class="box"><a class="count" href="#">56</a><a class="share" href="#">shares</a></div>
                    </div>
                </div>
            </div> <!-- about-->
            <div class="col-xs-12 col-md-4 form-subscribe">
<!--                <div class="text-left formBlockGate">-->
<!--                    <h3><a href="#logIn" name="login"> Войти </a> <a class="active" href="#signin" name="fsignin"> Зарегистрироватся</a></h3>-->
<!--                    <div class="fbody">-->
<!--                        <h2 class="text-center" style="color:#2d515b;margin-bottom:20px;">Заполни форму и получи видео-урок на почту!</h2>-->
<!--                        <!--  LOGIN FORM -->-->
<!--                        <form action="/course/Mark_de_Passorio/payment/" method="GET" class="formLand hidden" name="logIn">-->
<!--                            <center><span>Только для зарегестрированных пользователей</span></center>-->
<!--                            <div class="form-group">-->
<!--                                <label for="iEmail" class="sr-only">Email</label>-->
<!--                                <input type="email" class="form-control input-lg" id="iEmail" name="email" placeholder="Email" value="" required="">-->
<!--                            </div>-->
<!--                            <div class="form-group" id="require_pass">-->
<!--                                <label for="iPass" class="sr-only">Пароль</label>-->
<!--                                <input type="password" class="form-control input-lg" id="iPass" name="pasw" placeholder="Пароль">-->
<!--                            </div>-->
<!---->
<!--                            <div class="form-group">-->
<!---->
<!---->
<!--                                <input type="hidden" name="courseType" id="courseOline" value="online">-->
<!--                                <input type="hidden" name="course_price" id="course_price" value="0">-->
<!--                                <input type="hidden" name="course_offline_price" id="course_offline_price" value="0">-->
<!--                            </div>-->
<!--                            <center>-->
<!--                                <button type="submit" class="btn btn-primary btn-lg" style="font-size:18pt;">Отправить</button>-->
<!--                            </center>-->
<!--                            <div class="form-group">-->
<!--                                <center>-->
<!--                                    <a name="goto" href="/users/forgot/" class="flr">Забыли пароль?</a>-->
<!--                                </center>-->
<!--                            </div>-->
<!--                            <input type="hidden" value="Mark_de_Passorio" name="course">-->
<!--                        </form>-->
<!--                        <!-- SIGN IN FORM  -->-->
<!---->
<!--                        <form action="/course/Mark_de_Passorio/payment/" id="ajax_test" class="formLand" name="fsignIn" onsubmit="handleOutboundLinkClicks();return true;">-->
<!---->
<!--                            <div class="form-group">-->
<!---->
<!--                                <label for="iName" class="sr-only">Ваше имя</label>-->
<!--                                <input type="text" class="form-control input-lg" id="fiName" name="name" placeholder="Имя" value="" required="true" autocomplete="off">-->
<!--                            </div>-->
<!--                            <div class="form-group">-->
<!--                                <label for="iTel" class="sr-only">Телефон</label>-->
<!--                                <input type="text" class="form-control input-lg" id="fiTel" name="tel" placeholder="Телефон" value="" autocomplete="off">-->
<!--                            </div>-->
<!--                            <div class="form-group">-->
<!--                                <label for="iEmail" class="sr-only">Email</label>-->
<!--                                <input type="email" class="form-control input-lg" id="fiEmail" name="email" placeholder="Email" value="" autocomplete="off">-->
<!--                            </div>-->
<!---->
<!--                            <div class="form-group">-->
<!---->
<!---->
<!--                                <input type="hidden" name="courseType" id="courseOline" value="online">-->
<!--                                <input type="hidden" name="course_price" id="course_price" value="0">-->
<!--                                <input type="hidden" name="course_offline_price" id="course_offline_price" value="0">-->
<!--                            </div>-->
<!---->
<!--                            <div class="form-group hide">-->
<!--                                <label for="agreement" class="agreement">-->
<!--                                    <input type="checkbox" id="agreement" name="agreement" checked="checked"> я согласен с лицензионным соглашением-->
<!--                                </label>-->
<!--                            </div>-->
<!--                            <div class="warning hidden">-->
<!--                                <center>-->
<!--                                    <span class="warning"> Заполните все поля в форме </span>-->
<!--                                </center>-->
<!--                            </div>-->
<!--                            <center>-->
<!---->
<!--                                <span onclick="checkFirstForm();" class="btn btn-primary btn-lg" style="font-size:18pt;" id="fakebutton">Отправить</span>-->
<!---->
<!--                            </center>-->
<!---->
<!--                            <input type="hidden" value="Mark_de_Passorio" name="course">-->
<!---->
<!--                        </form>-->
<!--                        <div class="shtora"><h4>Вы ввели :</h4>-->
<!--                            <br>-->
<!--                            <p></p>-->
<!---->
<!--                            <span>Вам автоматически будет <b>сгенерирован</b> и отправлен <b>пароль на</b> указанную вами <b>почту</b></span><br>-->
<!--                            <span class="hide"><b>Вы согласились </b><a href="#">лицензионным соглашением</a></span>-->
<!--                            <br>-->
<!--                            <span><b>Ваши</b> личные <b>данные не будут переданы</b> третьим лицам</span>-->
<!--                            <!-- -->-->
<!--                            <form action="/course/Mark_de_Passorio/payment/" method="GET" name="mirrow" class="formConformSignin">-->
<!---->
<!--                                <input type="hidden" name="name">-->
<!--                                <input type="hidden" name="tel" value="+380">-->
<!--                                <input type="hidden" name="email">-->
<!--                                <input type="hidden" name="agreement" checked="checked" value="on">-->
<!--                                <div class="form-group">-->
<!--                                    <input type="hidden" name="courseType" id="courseOline" value="online">-->
<!--                                    <input type="hidden" name="course_price" id="course_price" value="0">-->
<!--                                    <input type="hidden" name="course_offline_price" id="course_offline_price" value="0">-->
<!--                                </div>-->
<!--                                <center>-->
<!--                                    <span onclick="backFirstForm();" class="btn btn-primary btn-lg" style="font-size:18pt;"><span class="glyphicon glyphicon-pencil"></span>ред.</span>-->
<!--                                    <button class="btn btn-primary btn-lg" style="font-size:18pt;" onclick="ga('send', 'event', 'FreeMasterClass', 'submit', getAvaliableH1());">Отправить</button>-->
<!--                                </center>-->
<!---->
<!--                                <input type="hidden" value="Mark_de_Passorio" name="course">-->
<!--                            </form>-->
<!--                            <!-- -->-->
<!--                        </div>-->
<!--                        <!-- end FORM  -->-->
<!---->
<!--                    </div>-->
<!--                </div>-->
            </div>



        </div>
    </div> <!--cover-->
</div>
<div style="background:url();background-size:cover;">
    <div style="background:rgba(255,255,255,0.9);height:100%;width:100%;padding:30px 0;">
        <div class="container">


            <div class="col-sm-12 l2Program">
                <h1>
                    <?= Yii::t('app', 'program') ?>
                </h1>
                <ul>
                    <?= $model->content ?>
                </ul>
            </div>





        </div>
    </div> <!--cover-->
</div>
<div style="background-image:url(<?= $owner->image ?>);min-height:500px;background-size:cover;/*background-position: 50% 50%;*/background-repeat:no-repeat;">



    <div class="container">

        <div class="col-md-5">
            <div class="text-left" style="margin-top:20px;background:#faf9e6;width:100%;">

                <div style="padding:10px 30px;">
                    <h2 class="text-center" style="color:#c2b409;margin-bottom:20px;">Заполни форму и получи видео-урок на почту!</h2>
                    <br>
                    <?=
                    $this->render(
                            '/course/toCartForm', [
                                'model' => $model,
                                'showPrice' => false,
                                'glyphiconSize' => 20
                            ])
                    ?>
                    <br>
                </div>
                <br>
            </div>
            <br>
            <br>
        </div>

        <div class="col-md-7">
            &nbsp;
            <br>
            <br>
        </div>


    </div>
</div>
<div id="comment" style="background:#fff;padding:30px 0;">


    <div class="container">
        <h3 id="comments">
            <?= Yii::t('app', 'comments') ?>
        </h3>

    </div>


</div>