common/models/Recipe.php
<?php

namespace common\models;

use Yii;
//use common\components\ImageBehavior;
use common\components\CMultilingualBehavior;
use omgdef\multilingual\MultilingualQuery;

/**
 * This is the model class for table "recipe".
 *
 * @property integer $id
 * @property string $image
 * @property integer $status
 */
class Recipe extends \yii\db\ActiveRecord
{
    public
        $width = 115,
        $height = 115;

    public function behaviors()
    {
        return [
//            ImageBehavior::className(),
            'ml' => [
                'class' => CMultilingualBehavior::className(),
                'languages' => Lang::getMap(),
                'languageField' => 'language',
                'langClassName' => RecipeLang::className(),
                'langForeignKey' => 'owner_id',
                'tableName' => 'recipe_lang',
                'attributes' => [
                    'name',
                    'description',
                    'short_description',
                    'meta_title',
                    'meta_keywords',
                    'meta_description',
                ]
            ],
        ];
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'recipe';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [
                'image',
                'required',
                'when' => function($model){return $model->isNewRecord; },
                'whenClient' => '
                    function(){
                        return document.
                            getElementsByClassName("file-input")[0]
                            .classList
                            .contains("file-input-new");
                    }'
            ],
            [['status'], 'required'],
            [['status'], 'integer'],
            [['image'], 'file', 'extensions'=>'jpg, gif, png', 'maxSize' => 1024 * 1024],
            [['meta_title', 'meta_keywords', 'meta_description'], 'string', 'max' => 255],
            [['name'], 'string', 'max' => 64],
            [['content'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'image' => Yii::t('app', 'Image'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

    /**
     * @inheritdoc
     * @return RecipeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new MultilingualQuery(get_called_class());
    }

//    public function preparePath($extension)
//    {
//        return Yii::$app->params['uploadPathRecipe'] . Yii::$app->getSecurity()->generateRandomString(6) . '.' .$extension;
//    }

    public function getRecipeLangs()
    {
        return $this->hasMany(RecipeLang::className(), ['owner_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGalleryItem()
    {
        return $this->hasMany(RecipeGalleryItem::className(), ['owner_id' => 'id']);
    }
}

common/controllers/RecipeController.php
<?php

namespace common\controllers;

use Yii;
use common\models\Recipe;
use common\models\RecipeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;

/**
 * RecipeController implements the CRUD actions for Recipe model.
 */
class RecipeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Recipe models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RecipeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Recipe model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $this->layout = 'main';
        $model = $this->findModel($id);
        $dataProvider = new ActiveDataProvider([
            'query' => $model->getGalleryItem(),
            'pagination' => [
                'pageSize' => 4
            ]
        ]);

        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Creates a new Recipe model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Recipe();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Recipe model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = Recipe::find()->where(['id' => $id])->multilingual()->one();;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Recipe model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Recipe model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Recipe the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Recipe::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/recipe/gallery_row.php
<?
use yii\widgets\ListView;
use yii\helpers\Html;

$dataProvider->pagination->page = $page;
$dataProvider->refresh();


?>
<?= ListView::widget([
    'dataProvider' => $dataProvider,
    'layout' => '{items}',
    'options' => [
        'class' => ['item', 'row', !$page ? 'active' : '']
//        'class' => ['item', 'row', 'active']
    ],
    'itemOptions' => [
        'class' => [
            'slide_block',
            'col-md-3',
            'col-sm-4',
            'col-xs-12'
        ]
    ],
    'itemView' => function($model) use ($dataProvider){
        return Html::a(
            false,
            $model->image,
            [
                'style' => "background-image: url($model->image)",
                'rel' => 'galleryBox'
            ]);
    }

])?>

frontend/views/recipe/index.php
<?
use yii\widgets\ListView;

$this->title = Yii::t('app', 'recipes');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="col-md-9">
    <form class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">

                <div class="inner-addon left-addon">
                    <i class="glyphicon glyphicon-search"></i>
                    <input type="search" class="form-control btn-md" id="searchRecipe" name="sn" placeholder="Поиск рецептов">
                </div>
                <small>Пример поиска:
                    <span class="link-dashed" onclick="$('#searchRecipe').val(this.innerHTML)">выпечка</span>,
                    <span class="link-dashed" onclick="$('#searchRecipe').val(this.innerHTML)">бисквиты</span>
                </small>
            </div>
            <div class="col-md-2"><button type="submit" class="btn btn-primary">Найти</button></div>

            <div class="pull-right">
                <small>Сортировка по: &nbsp;&nbsp;<span class="link-dashed">дате</span> <span class="caret"></span></small>
            </div>
        </div>
    </form>

    <?=
    ListView::widget([
        'dataProvider' => $dataProvider,
        'layout' => '{items}',
        'options' => [
            'tag' => null,
        ],
        'itemOptions' => [
            'tag' => 'div',
            'class' => 'col-sm-4'
        ],
        'itemView' => 'recipeItem'
    ])
    ?>
</div>
<div class="col-md-3">
    <h3>Рецепты по разделам</h3>
    <div style="line-height:30px;margin-bottom:20px;">
        <a href="/recipes/?sn=глазурь" class="btn btn-primary btn-sm">глазурь</a>
        <a href="/recipes/?sn=шоколад" class="btn btn-primary btn-sm">шоколад</a>
        <a href="/recipes/?sn=декор" class="btn btn-primary btn-sm">декор</a>
        <a href="/recipes/?sn=выпечка" class="btn btn-primary btn-sm">выпечка</a>
        <a href="/recipes/?sn=пирожное" class="btn btn-primary btn-sm">пирожное</a>
        <a href="/recipes/?sn=макаронс" class="btn btn-primary btn-sm">макаронс</a>
        <a href="/recipes/?sn=эклер" class="btn btn-primary btn-sm">эклер</a>
        <a href="/recipes/?sn=бисквит" class="btn btn-primary btn-sm">бисквит</a>
        <a href="/recipes/?sn=песочное тесто" class="btn btn-primary btn-sm">песочное тесто</a>
        <a href="/recipes/?sn=торт" class="btn btn-primary btn-sm">торт</a>
    </div>
    <div>
        <?= $this->render('/course/subscribeForm') ?>
    </div>
    <div class="btnSocial">
        <?= $this->render('/site/socialButtons', ['class' => 'col-sm-6 text-center social-follow-ico']) ?>
    </div>
</div>

frontend/views/recipe/recipeItem.php
<?
use common\components\CUrl;
?>
<a href='<?= CUrl::to(['recipe/view', 'id' => $model->id]) ?>'>
    <div class='recipeBlock' style='background-image:url(<?= $model->image ?>);background-size: cover; background-position: 50% 50%;'>
        <div class='recipeCover col-md-5'>
            <div class='recipeTitle'><?= $model->name ?></div>
            <div class="text-right recipe-cart-wrap">
<!--                <form action="">-->
<!--                    <button class>some</button>-->
<!--                </form>-->
                <span class="glyphicon glyphicon-shopping-cart"></span>
            </div>
            <div style='position:absolute; bottom:15px; left:0;font-size:10pt;width:90%;'>
                <div class='text-left col-xs-6'>
                    <?= Yii::$app->formatter->asDate($model->date) ?>
                </div>
                <div class='text-right col-xs-6'>
                    <span class='glyphicon glyphicon-comment'></span> <?= $model->count_comment ?>
                    <span class='glyphicon glyphicon-eye-open'></span> <?= $model->count_view ?>
                </div>
            </div>
        </div>
    </div>
</a>

frontend/views/recipe/view.php
<?
use yii\widgets\Breadcrumbs;
use common\components\CUrl;
use frontend\assets\GalleryAsset;

$this->title = $model->name;
$this->params['breadcrumbs'][] = [
    'label' => 'Рецепты',
    'url'   => CUrl::to(['recipe/index'])
];
$this->params['breadcrumbs'][] = $model->name;

GalleryAsset::register($this);
?>
<div class="container">
    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        'homeLink' => [
            'label' => 'Международная Кулинарная Академия',
            'url'   => CUrl::to(['site/index'])
        ]
    ]) ?>



    <!-- рецепты -->
    <div class="row">
        <div class="col-md-7">
            <div class="recept_main_picture">
                <img src="<?= $model->image ?>" style="ma-height:500px;max-width:100%;">
            </div>
        </div>
        <div class="col-md-5 recept_desc">
            <h1 ><?= $model->name ?></h1>

            <p><?= $model->short_description ?></p>

            <div class="share_block">
                <div id="maxShare">
                    <div id="facebook" data-url="" data-text="Нежный кофейный пирог от Филиппа Контичини" data-title="Share"></div>

                    <div id="comment">
                        <div class="box"><a class="count" name="comment_count" href="#comments">
                                <?= $model->count_comment ?>
                            </a>
                            <a class="share" href="#comments">COMMENT</a>
                        </div>
                    </div>

                    <div id="views">
                        <div class="box">
                            <a class="count" href="#">
                                <?= $model->count_view ?>
                            </a>
                            <a class="share" href="#">views</a>
                        </div>
                    </div>

                    <div id="shares">
                        <div class="box"><a class="count" href="#">
                                <?= $model->count_like ?>
                            </a>
                            <a class="share" href="#">shares</a>
                        </div>
                    </div>

                </div>



            </div>
        </div>

    </div>
<!-- рецепты -->

</div>


<div class="slider visible-md visible-lg">
    <div class="container">
        <div class="row" style="margin-top:20px;">
            <div class="col-md-12">
                <div id="recept_slider" class="carousel slide"  data-interval="false" data-ride="carousel">
                    <!-- Содержимое слайдов -->
                    <div class="carousel-inner">
                        <?
                            $count = $dataProvider->getTotalCount();

                            for($i = 0; $i<=$count/4; $i++)
                            {
                                echo $this->render(
                                    'gallery_row',
                                    [
                                        'dataProvider' => $dataProvider,
                                        'page' => $i
                                    ]
                                );
                            }
                        ?>
                    </div>

                    <!-- Controls -->

                    <a class="left carousel-control" href="#recept_slider" data-slide="prev">
                        <span class="slide_left_ico"></span>
                    </a>
                    <a class="right carousel-control" href="#recept_slider" data-slide="next">
                        <span class="slide_right_ico"></span>
                    </a>

                    <div class="clearfix"></div>

                    <div class="slide_name_block">
                        <span class="photo_num"><?= $count ?> фото</span>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="Instruction">
            <h2><?= $model->name ?></h2>
            <div class="recipes_text">
                <?= $model->description ?>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div>
            <?= $this->render('/course/subscribeForm') ?>
        </div>
        <div class="btnSocial">
            <?= $this->render('/site/socialButtons',
                ['class' => 'col-sm-6 text-center social-follow-ico']) ?>
        </div>
    </div>
</div>
<div class="container">



    <div class="col-md-3 hide">
        &nbsp;1
    </div>

    <div class="col-md-9">
        <h3 id="comments">Комментарии</h3>

    </div>


    <div class="col-md-3 hide">
        &nbsp;2
    </div>
</div>