common/models/Cart.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "cart".
 *
 * @property integer $id
 * @property integer $owner_id
 * @property integer $course_id
 * @property integer $status
 *
 * @property User $owner
 * @property Course $course
 */
class Cart extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cart';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
//        return [
//            [['owner_id', 'course_id', 'status'], 'required'],
//            [['owner_id', 'course_id', 'status'], 'integer'],
//            [['owner_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['owner_id' => 'id']],
//            [['course_id'], 'exist', 'skipOnError' => true, 'targetClass' => Course::className(), 'targetAttribute' => ['course_id' => 'id']],
//        ];
        return [
            [['owner_id', 'status'], 'required'],
            [['owner_id', 'status'], 'integer'],
            [['owner_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['owner_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'owner_id' => 'Owner ID',
//            'course_id' => 'Course ID',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOwner()
    {
        return $this->hasOne(User::className(), ['id' => 'owner_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
//    public function getCourse()
//    {
//        return $this->hasOne(Course::className(), ['id' => 'course_id']);
//    }

    public function beforeSave($insert)
    {
        $favorite_model = Favorite::findOne([
            'owner_id' => $this->owner_id,
            'course_id' => $this->course_id
        ]);

        return $favorite_model
            ? $favorite_model->delete()
            : true;
    }
}

common/controllers/CartController.php
<?php

namespace common\controllers;

use Yii;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use common\models\Cart;
use common\models\User;
use common\models\Order;
use yii\web\NotFoundHttpException;
use common\components\CUrl;
use common\models\Payment;
use common\models\Lang;

class CartController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST', 'GET'],
                    'discount' => ['POST'],
//                    'payment' => ['POST']
                ],
            ],
        ];
    }

    /**
     * Lists all Chef models.
     * @return mixed
     */
    public function actionIndex()
    {
        if(Yii::$app->user->isGuest)
            return $this->redirect('/user/login');

        $user = Yii::$app->user->identity;
        $order = $user->currentOrder ?: (new Order())->crelink();

        if($user->currentOrder && $user->currentOrder->status == Order::STATUS_SENT)
            return $this->redirect('cart/payment');

        $this->layout = 'main';

        Url::remember();



        $discount_persent = $order ? $order->discount_persent : 0;

//        $total -= $total * $discount_persent / 100;
        $total = $user->getTotalCartSum(true);

        $dataProvider = new ActiveDataProvider([
            'query' => $user->getCourses()
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'total' => $total,
            'discount' => $discount_persent
        ]);
    }

    /**
     * Displays a single Chef model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id = null)
    {
        if(Yii::$app->user->isGuest)
            return $this->goHome();

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionDiscount()
    {
        $user = Yii::$app->user->identity;

        $order = $user->currentOrder ?: (new Order())->crelink();

        if($order->discount_persent)
        {
            $order->discount_persent = 0;
            $user->discount = 1;
            $order->save();

        }
        else if($user->discount && !$order->discount_persent)
        {
            $order->discount_persent = Order::DISCOUNT_PERSENT;
            $user->discount = -1;
            $order->save();
        }

        return $this->redirect(CUrl::to(['cart/index']));
    }

    /**
     * Deletes an existing Chef model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id of course
     * @return mixed
     */
    public function actionDelete($id)
    {
        if(Yii::$app->user->isGuest)
            return $this->redirect(CUrl::to(['site/index']));

        $admin_id = User::ADMIN_ID;
        $user_id = Yii::$app->user->identity->id;

        $params = ($admin_id == $user_id)
            ? ['id' => $id]
            : ['course_id' => $id, 'owner_id' => $user_id];

        Cart::findOne($params)->delete();
        // TODO set flash with url to deleted course
        return $this->redirect(CUrl::to(['cart/index']));
    }

    public function actionPayment($post_action = false)
    {
        if(Yii::$app->user->isGuest)
            return $this->redirect(CUrl::to(['site/index']));

        $user = Yii::$app->user->identity;

        if(empty($user->cartItems))
            return $this->redirect(CUrl::to(['cart/index']));

        $order = $user->currentOrder;

        if($post_action == 'cancel')
        {
            $order->prepareToPay(Order::STATUS_CREATED);
            return $this->redirect(CUrl::to(['cart/index']));
        }

        $order->prepareToPay(Order::STATUS_SENT);

        $total = $order->getTotalCartSum(true);

        $dataProvider = new ActiveDataProvider(['query' => $order->getCourses()]);

        $payment = new Payment();

        return $this->render('/cart/payment',[
            'order' => $order,
            'dataProvider' => $dataProvider,
            'total' => $total,
            'payment' => $payment
        ]);
    }

    /**
     * Finds the Cart model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cart the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Cart::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/cart/disableDiscountForm.php
<?
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use common\components\CUrl;
?>

<? ActiveForm::begin(['action' => CUrl::to(['/cart/discount'])]) ?>

<?= Html::submitButton('Использовать скидку в другой раз', [
    'class' => 'btn btn-danger',
    'disabled' => !$wasDiscountUsed
]) ?>

<? ActiveForm::end() ?>

frontend/views/cart/discountForm.php
<?
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use common\components\CUrl;
?>

<? ActiveForm::begin(['action' => CUrl::to(['/cart/discount'])]) ?>

<?= Html::submitButton(Yii::t('app', 'use_discount'), [
    'class' => 'btn btn-primary',
    'disabled' => $wasDiscountUsed,
    'title' => $wasDiscountUsed ? 'К сожалению, использовать можно не более одной скидки за заказ' : false
]) ?>

<? ActiveForm::end() ?>

frontend/views/cart/discountInfo.php
<div class="row">
    <div class="col-md-12">
        <h3 class="h3 text-danger">
            <?=
            $disCount
                ? Yii::t(
                    'app',
                    'У Вас есть {n, plural, one{# скидка} other{# скидки}}!',
                    ['n' => $disCount])
                : ''
            ?>
        </h3>
    </div>
</div>
<div class="row" style="padding:20px 25px;">
    <div class="col-sm-5" style="padding:0">
        <?=
            !$discount
                ? $this->render('discountForm', ['wasDiscountUsed' => $discount > 0])
                : $this->render('disableDiscountForm', ['wasDiscountUsed' => $discount > 0])
        ?>
    </div>
    <div class="col-sm-7 total">
        <span class="total_lbl">К оплате <?= $itemCount ?> видео: </span>
        <span class="total_price"><?= Yii::$app->formatter->asDecimal($total) ?> €</span><br>
    </div>
</div>

frontend/views/cart/index.php
<?
use yii\widgets\ListView;
use yii\widgets\Breadcrumbs;
use common\components\CUrl;
use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->title = Yii::t('app', 'cart');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <?= Breadcrumbs::widget([
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        'homeLink' => [
            'label' => 'Международная Кулинарная Академия',
            'url'   => CUrl::to(['site/index'])
        ]
    ]) ?>
    <div class="col-md-9">
        <div style="margin-bottom:30px; height:50px">
            <div class="steps active_step">
                <span><strong><?= Yii::t('app', 'step') ?> 1</strong><br>
                <?= Yii::t('app', 'ordering') ?>
                </span>
            </div>
            <div class="steps">
                <span><strong><?= Yii::t('app', 'step') ?> 2</strong><br>
                <?= Yii::t('app', 'payment') ?>
                </span>
            </div>
            <div class="steps">
                <span><strong><?= Yii::t('app', 'step') ?> 3</strong><br>
                <?= Yii::t('app', 'getting_access') ?>
                </span>
            </div>
            <br>
        </div>
        <div>
        <span>
            <h3 class="list_title">
                <?= $dataProvider->getCount()
                    ? Yii::t('app',
                        'you_added_n_mc',
                        ['n' => $dataProvider->getCount()])
                    : false
                ?>
            </h3>
        </span>
        </div>
        <?=
        ListView::widget([
            'dataProvider' => $dataProvider,
            'layout' => '{items}',
            'options' => ['tag' => null],
            'itemOptions' => ['tag' => null],
            'itemView' => function($model) use ($discount) {
                return $this->render('/course/cartItem', [
                    'model'     => $model,
                    'discount'  => $discount
                ]);
            },
            'emptyText' => 'В корзине пока нет мастер-классов',
            'emptyTextOptions' => ['tag' => 'h3']
        ])
        ?>

        <?=
        $this->render('discountInfo', [
            'itemCount' => $dataProvider->getCount(),
            'disCount'  => Yii::$app->user->identity->discount,
            'discount'  => $discount,
            'total'     => $total
        ])
        ?>
    </div>
    <div class="col-md-3">
        <div class="info_block">
            <span class="list_ico"></span>
            <p class="info_text">Вы получите моментальный доступ к оплаченным записям!</p>
        </div>
        <div class="info_block">
            <span class="list_ico"></span>
            <p class="info_text">Вы сможете наблюдать за мастер-классом и задавать вопросы в режиме реального времени!</p>
        </div>

        <div class="pay_start_block">
            <? $form = ActiveForm::begin(['action' => CUrl::to(['cart/payment'])]); ?>
                <span class="total_sum_lbl">Сумма к оплате:</span>
                <span class="total_sum_price"><?= Yii::$app->formatter->asDecimal($total) ?> €</span>
            <?= Html::submitButton('Перейти к оплате', [
                'class' => 'btn go_pay',
                'name'  => 'go_pay',
                'disabled' => !$dataProvider->count
            ]) ?>
            <span class="total_sum_info">или вернуться к </span>
            <a href='<?= CUrl::to(['course/online']) ?>' class="total_sum_back">каталогу видео</a>
            <? ActiveForm::end(); ?>
<!--            <form action="/cart-payment/" method="post">-->
<!--                <span class="total_sum_lbl">Сумма к оплате:</span>-->
<!--                <span class="total_sum_price">--><?//= Yii::$app->formatter->asDecimal($total) ?><!-- €</span>-->
<!--                <input class="btn go_pay" type="submit" name="go_pay" value="Перейти к оплате">-->
<!--                <span class="total_sum_info">или вернуться к </span>-->
<!--                <a href='--><?//= CUrl::to(['course/online']) ?><!--' class="total_sum_back">каталогу видео</a>-->
<!--            </form>-->

        </div>
    </div>
</div>
<div class="container payment_description">
    <div class="col-sm-1 col-sm-offset-2">
        <img src="/image/question_ico.png">
    </div>
    <div class="col-sm-9" style="padding-left:30px">
        <div class="phone_block">
            <h3 style="margin-top:0;">Необходима техническая помощь с оплатой?</h3>
            Напишите нам на почту <a href="mailto:webinar.kica@gmail.com">webinar.kica@gmail.com</a> или позвоните по телефону:<br>
            <table cellpadding="5" cellspacing="0">
                <tbody><tr>
                    <td>Россия:</td>
                    <td>+7 499 350 26 86</td>
                </tr>
                <tr>
                    <td>Украина:</td>
                    <td>+38 063 237 01 10, <br>
                        +38 044 237 01 10</td>
                </tr>
                </tbody></table>
        </div>
    </div>
</div>

frontend/views/cart/payment.php
<?
use common\components\CUrl;
use yii\widgets\ListView;
use yii\widgets\ActiveForm;

$this->title = 'Оплата заказа';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container" style="min-height:600px;">

    <div class="col-md-9">
        <div style="margin-bottom:30px; height:50px">
            <div class="steps">
                    <span><strong>Шаг 1</strong><br>
                    Оформление заказа
                    </span>
            </div>
            <div class="steps active_step2">
                    <span><strong>Шаг 2</strong><br>
                    Оплата
                    </span>
            </div>
            <div class="steps">
                    <span><strong>Шаг 3</strong><br>
                    Получение доступа
                    </span>
            </div>
            <br>
        </div>

        <div>

            <span class="payment_list_title">Проверьте Ваш заказ:</span>
        </div>


        <div class="text-center lead row">
            <a href='<?= CUrl::to(['cart/payment', 'post_action' => 'cancel']) ?>' class="btn btn-danger pull-right">Изменить заказ</a>
            <div class="alert-info col-md-8 col-md-offset-2" style="padding:20px;">
                Заказ номер <?= $order->id ?>, к оплате  <span class="total_price"><?= $total ?> €</span>
            </div>
        </div>
        <?=
        ListView::widget([
            'dataProvider' => $dataProvider,
            'layout' => '{items}',
            'options' => null,
            'itemOptions' => null,
            'itemView' => '/course/payment_item'
        ])
        ?>
        <br>
        <h3>Выберите способ оплаты:</h3>


        <div class="row" style="min-height:160px;margin-top:5px;margin-bottom:20px;">
            <?= $this->render('form/apioplata',['disabled' => true]) ?>
            <?= $this->render('form/liqpay',['disabled' => true]) ?>
<!--            <div class="text-center col-sm-6 col-xs-12 col-md-3">-->
<!--                <a href="/payment/confirm/?order=234566"><input type="image" src="/img/payment4.png"></a>-->
<!--            </div>-->
            <?= $this->render('form/paypal',[
                'order' => $order,
                'payment' => $payment,
                'price' => $total
            ]) ?>
        </div>

    </div>


    <div class="col-md-3">
        <div class="payment_info_block">
            <center>
                <img src="/img/question_black.png">
            </center>
            <h3>Необходима техническая помощь с оплатой?</h3>
            Напишите нам на почту <a href="mailto:webinar.kica@gmail.com">webinar.kica@gmail.com</a><br>или позвоните по телефону:<br>
            <table>
                <tbody><tr>
                    <td>Россия:</td>
                    <td>+7 499 350 26 86</td>
                </tr>
                <tr>
                    <td>Украина:</td>
                    <td>+38 063 237 01 10<br>
                        +38 044 237 01 10</td>
                </tr>


                </tbody></table>
        </div>
    </div>

</div>